version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8085:8085"
    container_name: backend
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    container_name: frontend
    networks:
      - mynetwork
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8085

networks:
  mynetwork:
